WITH 
UOLB_UOLC AS (
SELECT
  FIN01.COMP_CODE, 
  FIN01.FISCPER, 
  FIN01.PSTNG_DATE,  
  FIN01.ACCOUNT, 
  FIN01.AC_DOC_TYP, 
  FIN01.DEBIT_LC, 
  FIN01.CREDIT_LC, 
  FIN01._BIC_CA_PLTINS,
  -- FIN01.AC_DOC_NO,
  FIN01._BIC_CA_OFERTA, 
  FIN01.MATERIAL, 
  FIN01.PROFIT_CTR, 
FROM uolcs-datalake-engcorp-prd.`ecc_fi_sapphm_raw.OFIN01` FIN01
WHERE EXTRACT(YEAR FROM PSTNG_DATE) = 2024
)
, REC AS (
SELECT 
  COMP_CODE, 
  FISCPER, 
  _BIC_CA_PLTINS AS ID_INSCRIPTION,
  PSTNG_DATE, 
  ACCOUNT, 
  AC_DOC_TYP, 
  -- AC_DOC_NO,
  _BIC_CA_OFERTA, 
  MATERIAL, 
  PROFIT_CTR, 
  DEBIT_LC, 
  CREDIT_LC, 
  NULL AS DEBIT_LC_1, 
  NULL AS CREDIT_LC_1 
FROM UOLB_UOLC
)

, STAR_JOIN AS (
SELECT 
  COMP_CODE, 
  FISCPER, 
  ID_INSCRIPTION,
  PSTNG_DATE, 
  ACCOUNT,   
  -- AC_DOC_NO AS NUM_DOC_CONTABIL,
  _BIC_CA_OFERTA, 
  REC.MATERIAL, 
  PROFIT_CTR, 
  CASE WHEN AC_DOC_TYP = 'RV' THEN IFNULL(CREDIT_LC,0)+ IFNULL(CREDIT_LC_1,0) ELSE 0 END - 
  CASE WHEN AC_DOC_TYP = 'RV' THEN  IFNULL(DEBIT_LC,0)+ IFNULL(DEBIT_LC_1,0) ELSE 0 END + 
  CASE WHEN AC_DOC_TYP != 'RV' THEN  IFNULL(DEBIT_LC,0)+ IFNULL(DEBIT_LC_1,0) ELSE  0 END - 
  CASE WHEN AC_DOC_TYP != 'RV' THEN  IFNULL(CREDIT_LC,0)+ IFNULL(CREDIT_LC_1,0) ELSE 0 END AS TOTAL_SALDO
FROM REC
)


SELECT
  COMP_CODE,
  FISCPER, 
  ID_INSCRIPTION,
  PSTNG_DATE,
  REC._BIC_CA_OFERTA AS OFERTA,
  REC.ACCOUNT,
  REC.MATERIAL,
  REC.PROFIT_CTR,
  CL.txtmd AS DESCRICAO_CENTRO_LUCRO,
  OP._BIC_CA_UNNEG AS UNIDADE_DE_NEGOCIO,
  OP._BIC_CA_PROPDD AS DESCRICAO_MATERIAL,
  CONT.ACCOUNT_DESCRICAO as DESCRICAO_ACCOUNT,
  off.txtlg as DESCRICAO_OFERTA,
  SUM(TOTAL_SALDO * -1) AS SALDO
FROM STAR_JOIN AS REC
LEFT JOIN uolcs-datalake-engcorp-prd.`ecc_fi_sapphm_raw._BIC_AOPRO0100` AS OP
ON REC.MATERIAL = OP.MATERIAL
LEFT JOIN uolcs-datalake-engcorp-prd.`ecc_financeiro_gl_report.CV_DM_ACCOUNT` AS CONT
ON REC.ACCOUNT = CONT.ACCOUNT_ACC
LEFT JOIN uolcs-datalake-engcorp-prd.`ecc_fi_sapphm_raw._BIC_TCA_OFERTA` AS OFF
ON REC._BIC_CA_OFERTA = OFF._BIC_CA_OFERTA
LEFT JOIN uolcs-datalake-engcorp-prd.`ecc_fi_sapphm_raw._BI0_TPROFIT_CTR` AS CL
ON REC.PROFIT_CTR = CL.PROFIT_CTR AND CL.DATETO ='9999-12-31'
WHERE COMP_CODE = 'UOLB'
AND REC.ACCOUNT >= '0040000000' AND REC.ACCOUNT <= '0049999999'
AND EXTRACT(YEAR FROM DATE(PSTNG_DATE)) = 2024
GROUP BY COMP_CODE,
  FISCPER, 
  PSTNG_DATE,
  REC._BIC_CA_OFERTA,
  REC.ACCOUNT,
  REC.MATERIAL,
  REC.PROFIT_CTR,
  CL.txtmd,
  OP._BIC_CA_UNNEG,
  OP._BIC_CA_PROPDD,
  CONT.ACCOUNT_DESCRICAO,
  OFF.txtlg,
  ID_INSCRIPTION

  -- Com consumo menor de 33GB
