WITH
DOCUMENTOS (TIPDOC, FILDOC, SERDOC, CODDOC, PLACA, PROPRI, CODCLI)
AS

	(
		SELECT
			'CTRC' AS 'TIPDOC',
			CON.CODFIL AS 'FILDOC',
			CON.SERCON AS 'SERDOC',
			CON.CODCON AS 'CODDOC',
			CON.PLACA AS 'PLACA',
			VEI.PROPRI AS 'VINCULO',
			CON.CODPAG AS 'CODCLI'
		FROM
			db_visual_rodopar.dbo.RODCON CON
			INNER JOIN db_visual_rodopar.dbo.RODVEI VEI ON CON.PLACA = VEI.CODVEI
		WHERE
			CON.SITUAC IN ('E','D') AND
			CON.TIPCON <> 'L'

		UNION ALL

		SELECT
			'OST' AS 'TIPDOC',
			ORD.CODFIL AS 'FILDOC',
			ORD.SERORD AS 'SERDOC',
			ORD.CODIGO AS 'CODDOC',
			ORD.PLACA AS 'PLACA',
			VEI.PROPRI AS 'VINCULO',
			ORD.CODPAG AS 'CODCLI'
		FROM
			db_visual_rodopar.dbo.RODORD ORD
			INNER JOIN db_visual_rodopar.dbo.RODVEI VEI ON ORD.PLACA = VEI.CODVEI
		WHERE
			ORD.SITUAC IN ('E','D','B')

		UNION ALL

		SELECT
			'MAN' AS 'TIPDOC',
			MAN.CODFIL AS 'FILDOC',
			MAN.SERMAN AS 'SERDOC',
			MAN.CODMAN AS 'CODDOC',
			MAN.PLACA AS 'PLACA',
			VEI.PROPRI AS 'VINCULO',
			(
			SELECT TOP 1 
				CASE
					WHEN IMA.TIPDOC = 'C' THEN 
												(
												SELECT TOP 1 CON.CODPAG
												FROM
													db_visual_rodopar.dbo.RODCON CON
												WHERE
													CON.CODFIL = IMA.FILDOC AND
													CON.SERCON = IMA.SERDOC AND
													CON.CODCON = IMA.CODDOC
												)
					WHEN IMA.TIPDOC = 'O' THEN 
												(
												SELECT TOP 1 ORD.CODPAG
												FROM
													db_visual_rodopar.dbo.RODORD ORD
												WHERE
													ORD.CODFIL = IMA.FILDOC AND
													ORD.SERORD = IMA.SERDOC AND
													ORD.CODIGO = IMA.CODDOC
												)
			ELSE NULL END 
			FROM
				db_visual_rodopar.dbo.RODIMA IMA
			WHERE
				IMA.FILMAN = MAN.CODFIL AND
				IMA.SERMAN = MAN.SERMAN AND
				IMA.CODMAN = MAN.CODMAN
			) AS 'CODCLI'
		FROM
			db_visual_rodopar.dbo.RODMAN MAN
			INNER JOIN db_visual_rodopar.dbo.RODVEI VEI ON MAN.PLACA = VEI.CODVEI
		WHERE
			MAN.SITUAC IN ('D','E','B')

		UNION ALL

		SELECT
			'LPR' AS 'TIPDOC',
			LPR.CODFIL AS 'FILDOC',
			'LPR' AS 'SERDOC',
			LPR.CODLPR AS 'CODDOC',
			LPR.PLACA AS 'PLACA',
			VEI.PROPRI AS 'VINCULO',
			LPR.CODTOM AS 'CODCLI'
		FROM
			db_visual_rodopar.dbo.RODLPR LPR
			INNER JOIN db_visual_rodopar.dbo.RODVEI VEI ON LPR.PLACA = VEI.CODVEI
		WHERE
			NOT(LPR.SITUAC IN ('C','I'))


	)

	SELECT
		'OCO' AS 'TIPO',
		GRO.TIPDOC AS 'TIPO_DOC',
		GRO.CODFIL AS 'FILGRO',
		GRO.CODGRO AS 'CODGRO',
		GRO.FILDOC AS 'CODFIL',
		GRO.SERDOC AS 'SERCON',
		GRO.CODDOC AS 'CODCON',
		OCO.FINENT AS 'FINALIZA',
		GRO.DATABE AS 'DATOCO',
		OCO.DESCRI,
		UPPER(DOC.PLACA) AS 'PLACA',
		DOC.CODCLI AS 'CODCLI'  
	FROM
		db_visual_rodopar.dbo.RODGRO GRO (NOLOCK)
		INNER JOIN db_visual_rodopar.dbo.RODOCO OCO (NOLOCK) ON GRO.CODOCO = OCO.CODIGO
		INNER JOIN DOCUMENTOS DOC (NOLOCK) ON GRO.TIPDOC = DOC.TIPDOC AND
											  GRO.FILDOC = DOC.FILDOC AND
											  GRO.SERDOC = DOC.SERDOC AND
											  GRO.CODDOC = DOC.CODDOC
	WHERE
		GRO.TIPDOC <> 'DEVA' AND
		DOC.PROPRI <> 'S' AND
		GRO.DATABE >= DATEADD(MONTH, -2, GETDATE()) AND GRO.DATABE <= GETDATE()