WITH KM_RODADO AS(
SELECT DISTINCT 
	CODVEI,
	DATHOR,
	(SELECT TOP 1 KMTVEI FROM db_visual_rodopar.dbo.RODVRA V 
	WHERE V.CODVEI = VRA.CODVEI AND V.DATHOR = VRA.DATHOR
	ORDER BY V.DATHOR DESC) AS KM_ATUAL
FROM 
	db_visual_rodopar.dbo.RODVRA VRA 
WHERE
	YEAR(VRA.DATHOR) >= 2024
)
SELECT 
	CODVEI,
	MAX(KM_ATUAL) - MIN(KM_ATUAL) AS KM_RODADO
FROM 
	KM_RODADO
WHERE
	KM_ATUAL > 0
GROUP BY
	CODVEI
