WITH 
Previsto AS(
SELECT 
	ORC.ID_ORC,
	ORC.MESANO,
	ORC.CODCGA,
	ORC.CODCUS,
	ORC.SINTET,
	ORC.ANALIT,
	ORC.DEBCRE,
	CASE 
		WHEN ORC.DEBCRE = 'D'THEN ORC.CMVLPR * -1 
		ELSE ORC.CMVLPR
	END AS Valor_Previsto,
	CASE 
		WHEN ORC.DEBCRE = 'D'THEN ORC.CMVLRE * -1
	ELSE ORC.CMVLRE
	END AS Valor_Realizado
FROM 
	db_visual_rodopar.dbo.ORCLAN ORC
),
Realizado AS(
SELECT
	FORMAT(REL.DATA,'MM/yyyy') AS MESANO,
	REL.DATA,
	REL.CODCUS,
	REL.CODCGA,
	CASE
		WHEN REL.ANALIT = 93 THEN 1
		ELSE REL.SINTET
	END AS SINTET,
	REL.ANALIT,
	CASE
		WHEN ANA.RECDES = 'R' THEN 'C'
		ELSE ANA.RECDES
	END AS DEBCRE,
	CAST(REL.VALOR AS DECIMAL(10,2)) AS Vlr_Realz
FROM 
	db_visual_rodopar.dbo.VW_GERENCIAL_COMPETENCIA_1 REL
LEFT JOIN
	db_visual_rodopar.dbo.PAGCLA ANA ON ANA.CODCLAP = REL.ANALIT
WHERE
	REL.CODEMP = 2
	AND YEAR(REL.DATA) >= 2024
),
Suplementacao AS (
SELECT 
    HIST.ID_HIST,
	HIST.MESANO,
	HIST.CODCGA,
	HIST.CODCUS,
	HIST.SINTET,
	HIST.ANALIT,
	HIST.DEBCRE,
	HIST.VLRSUP,
	CASE
		WHEN HIST.VLRSUP <> 0 AND HIST.TIPHIST IS NULL THEN 'Suplementação'
		WHEN HIST.VLRSUP <> 0 AND HIST.TIPHIST = 'TRA' THEN 'Transferencia'
		ELSE NULL
	END AS TIPO,
	HIST.TIPHIST
FROM 
	db_visual_rodopar.dbo.ORCLAN_HIST HIST
),
Previsto_Insert AS(
SELECT DISTINCT
    O.ID_ORC,
    O.MESANO,
    O.DATATU,
	O.CODUNN,
	O.CODCGA,
	O.CODCUS,
	O.SINTET,
	O.ANALIT,
    O.DEBCRE,
	
	CASE
		WHEN (SELECT SUM(VLRSUP) FROM db_visual_rodopar.dbo.ORCLAN_HIST HIST WHERE HIST.ID_ORC = O.ID_ORC) IS NULL THEN O.CMVLPR 
		ELSE (SELECT TOP 1 HIST.CMVLPR FROM db_visual_rodopar.dbo.ORCLAN_HIST HIST WHERE HIST.ID_ORC = O.ID_ORC AND HIST.MESANO = O.MESANO ORDER BY HIST.DATATU ASC) 
	END AS Valor_PrevistoInsert
FROM 
    db_visual_rodopar.dbo.ORCLAN O
LEFT OUTER JOIN 
    db_visual_rodopar.dbo.ORCTEM TEM ON O.CODTEM = TEM.CODTEM
),
Folha_Pagamento AS(
SELECT 
	CASE
		WHEN (SELECT TOP 1 CLA.CODCLAP FROM db_visual_rodopar.dbo.PAGCLA CLA WHERE CLA.CODCON = CONTAB.CTACON ORDER BY CODCLAP ASC) IS NULL THEN 50
		WHEN (SELECT TOP 1 CLA.CODCLAP FROM db_visual_rodopar.dbo.PAGCLA CLA WHERE CLA.CODCON = CONTAB.CTACON ORDER BY CODCLAP ASC) IN (419,29,423,218,424,380) THEN 50
		ELSE (SELECT TOP 1 CLA.CODCLAP FROM db_visual_rodopar.dbo.PAGCLA CLA WHERE CLA.CODCON = CONTAB.CTACON ORDER BY CODCLAP ASC)
	END AS ANALIT,
	(SELECT TOP 1 CLA.DESCRI FROM db_visual_rodopar.dbo.PAGCLA CLA WHERE CLA.CODCON = CONTAB.CTACON ORDER BY CODCLAP ASC) AS ANALITICO,
    CONTAB.CODFIL AS CODCGA,
	1 AS CODCUS,
	CONTAB.TIPCON,
	CONTAB.CTACON,
	CONTAB.COMPLE,
	CONTAB.VLRCON AS Valor_FolhaPagamento,
	FORMAT(CONTAB.DATCON, 'MM/yyyy') AS MESANO,
    CONLOT.TIPDOC, 
	CASE
		WHEN CONLOT.TIPDOC = 'FPG' THEN 26
		WHEN CONLOT.TIPDOC = 'CTF' THEN 1
		ELSE 0
	END AS SINTET,
    RODPLA.DESCRI 
FROM 
    db_visual_rodopar.dbo.CONTAB  (NOLOCK)
INNER JOIN 
    db_visual_rodopar.dbo.CONLOT (NOLOCK) ON CONLOT.NUMERO = CONTAB.CODLOT
INNER JOIN 
    db_visual_rodopar.dbo.RODFIL (NOLOCK) ON CONTAB.CODFIL = RODFIL.CODFIL
INNER JOIN 
    db_visual_rodopar.dbo.RODPLA (NOLOCK) ON CONTAB.CTACON = RODPLA.CODCON AND RODFIL.CODEMP = RODPLA.CODEMP

WHERE 
    CODIGO <> 0  
	AND CONLOT.TIPDOC IN ('FPG') -- Folha de pagamento
	AND CONTAB.CTACON LIKE '4%'
	AND YEAR(CONTAB.DATCON) >= 2024
)
SELECT
	PR.MESANO,
	PR.CODCGA,
	PR.CODCUS,
	PR.SINTET,
	PR.ANALIT,
	PR.DEBCRE,

	-- Valor de Previsto Inserido na tela Orçamentaria, essa consulta não sofre alteração de valores por meio de suplementação e nem transferencia.
	(SELECT SUM(PI.Valor_PrevistoInsert) FROM Previsto_Insert PI 
		WHERE PI.MESANO = PR.MESANO AND PI.CODCGA = PR.CODCGA AND PI.CODCUS = PR.CODCUS AND PI.SINTET = PR.SINTET AND PI.ANALIT = PR.ANALIT) AS Vlr_PrevistoInserido,

	PR.Valor_Previsto,

	-- Calculo de Realizado
	CASE
		WHEN PR.SINTET = 26 THEN 
	-- Valor de Realizado da Folha de Pagamento, sendo retirado do Modulo Contabil
		(SELECT SUM(FPG.Valor_FolhaPagamento) FROM Folha_Pagamento FPG 
			WHERE FPG.MESANO = PR.MESANO AND FPG.CODCGA = PR.CODCGA AND FPG.CODCUS = PR.CODCUS AND FPG.SINTET = PR.SINTET AND FPG.ANALIT = PR.ANALIT)
		ELSE
	-- Valor de Realizado, pegando o relatorio 221
		(SELECT SUM(RE.Vlr_Realz) FROM Realizado RE 
			WHERE RE.MESANO = PR.MESANO AND RE.CODCGA = PR.CODCGA AND RE.CODCUS = PR.CODCUS AND RE.SINTET = PR.SINTET AND RE.ANALIT = PR.ANALIT) 
	END AS Vlr_Realizado,

	-- Valor de Suplementação e Transferencia, pegando da tabela de Historico da Tela Orçamentaria
	(SELECT SUM(SUP.VLRSUP) FROM Suplementacao SUP 
		WHERE SUP.MESANO = PR.MESANO AND SUP.CODCGA = PR.CODCGA AND SUP.CODCUS = PR.CODCUS AND SUP.SINTET = PR.SINTET AND SUP.ANALIT = PR.ANALIT) AS Vlr_SupTra,

	-- Pegando o tipo de movimentação (Suplementação ou Transferencia) da tabela de Historico da Tela Orçamentaria
	(SELECT TOP 1 SUP.TIPO FROM Suplementacao SUP 
		WHERE SUP.MESANO = PR.MESANO AND SUP.CODCGA = PR.CODCGA AND SUP.CODCUS = PR.CODCUS AND SUP.SINTET = PR.SINTET AND SUP.ANALIT = PR.ANALIT) AS Tipo_SupTra

	--CASE
	--	WHEN PR.Valor_Realizado = 0 THEN 
	--	(SELECT SUM(Vlr_Realz) FROM Realizado RE 
	--	WHERE RE.MESANO = PR.MESANO AND RE.CODCGA = PR.CODCGA AND RE.CODCUS = PR.CODCUS AND RE.SINTET = PR.SINTET AND RE.ANALIT = PR.ANALIT)
	--	ELSE PR.Valor_Realizado
	--END Realizado
FROM Previsto PR
WHERE TRY_CAST(SUBSTRING(PR.MESANO, CHARINDEX('/', PR.MESANO) + 1, 4) AS INT) > 2024

